<a href="https://colab.research.google.com/github/tranvulamdev88/machine-learning/blob/main/tonghop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [119]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [120]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/voting-records/house-votes-84.data"
names = ['party', 'infants', 'water', 'budget', 'physician','salvador', 'religious', 'satellite', 'aid', 'missile',
        'immigration', 'synfuels', 'education', 'superfund', 'crime', 'duty_free_exports','eaa_rsa']
        
df = pd.read_csv(url, names = names)

df.head()

,party,infants,water,budget,physician,salvador,religious,satellite,aid,missile,immigration,synfuels,education,superfund,crime,duty_free_exports,eaa_rsa
0,republican,n,y,n,y,y,y,n,n,n,y,?,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,?
2,democrat,?,y,y,?,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,?,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,?,y,y,y,y

In [121]:
df.replace(('y', 'n', '?'), (1, 0, np.NaN), inplace=True)
df.head()

,party,infants,water,budget,physician,salvador,religious,satellite,aid,missile,immigration,synfuels,education,superfund,crime,duty_free_exports,eaa_rsa
0,republican,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,NaN,1.0,1.0,1.0,0.0,1.0
1,republican,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,NaN
2,democrat,NaN,1.0,1.0,NaN,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
3,democrat,0.0,1.0,1.0,0.0,NaN,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
4,democrat,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,NaN,1.0,1.0,1.0,1.0

In [122]:
df.fillna(method='bfill', inplace=True)
df.tail()

,party,infants,water,budget,physician,salvador,religious,satellite,aid,missile,immigration,synfuels,education,superfund,crime,duty_free_exports,eaa_rsa
430,republican,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0
431,democrat,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
432,republican,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0
433,republican,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0
434,republican,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,NaN,0.0

In [123]:
df.fillna(method='ffill', inplace=True)
df.tail()

,party,infants,water,budget,physician,salvador,religious,satellite,aid,missile,immigration,synfuels,education,superfund,crime,duty_free_exports,eaa_rsa
430,republican,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0
431,democrat,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
432,republican,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0
433,republican,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0
434,republican,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0

In [124]:
df.party.replace(('republican', 'democrat'), (1, 0), inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   party              435 non-null    int64
 1   infants            435 non-null    float64
 2   water              435 non-null    float64
 3   budget             435 non-null    float64
 4   physician          435 non-null    float64
 5   salvador           435 non-null    float64
 6   religious          435 non-null    float64
 7   satellite          435 non-null    float64
 8   aid                435 non-null    float64
 9   missile            435 non-null    float64
 10  immigration        435 non-null    float64
 11  synfuels           435 non-null    float64
 12  education          435 non-null    float64
 13  superfund          435 non-null    float64
 14  crime              435 non-null    float64
 15  duty_free_exports  435 non-null    float64
 16  eaa_rsa            435 non-null    float64
dtypes: float64(16), int64(1)
memory usage: 57.9 KB

In [125]:
for col in df.columns:
  df[col] = pd.to_numeric(df[col]).astype(int)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   party              435 non-null    int64
 1   infants            435 non-null    int64
 2   water              435 non-null    int64
 3   budget             435 non-null    int64
 4   physician          435 non-null    int64
 5   salvador           435 non-null    int64
 6   religious          435 non-null    int64
 7   satellite          435 non-null    int64
 8   aid                435 non-null    int64
 9   missile            435 non-null    int64
 10  immigration        435 non-null    int64
 11  synfuels           435 non-null    int64
 12  education          435 non-null    int64
 13  superfund          435 non-null    int64
 14  crime              435 non-null    int64
 15  duty_free_exports  435 non-null    int64
 16  eaa_rsa            435 non-null    int64
dtypes: int64(17)
memory usage: 57.9 KB

In [126]:
y = df.party.values # labels
X = df.drop('party', axis=1) # features

In [127]:
class Classifier:
  def __init__(self, X, y):
    from sklearn.model_selection import train_test_split
    self.Xtrain,self.Xtest,self.ytrain,self.ytest = train_test_split(X, y, test_size = 0.25, random_state = 42, stratify=y)
  
  def kNN(self, k = 5):
    print('KNN Algorithm')
    from sklearn.neighbors import KNeighborsClassifier
    KNN = KNeighborsClassifier(n_neighbors=k)
    KNN.fit(self.Xtrain, self.ytrain)
    self.y_pred = KNN.predict(self.Xtest)

    self.report()

  def svm(self, kernel = 'rbf'):
    print('SVM Algorithm')
    from sklearn.svm import SVC
    classifier = SVC(kernel = kernel)
    classifier.fit(self.Xtrain, self.ytrain)
    self.y_pred = classifier.predict(self.Xtest)

    self.report()

  def randomForest(self, n_estimators, criterion, random_state):
    print('Random Forest Algorithm')
    from sklearn.ensemble import RandomForestClassifier
    classifier = RandomForestClassifier(n_estimators = n_estimators, criterion = criterion, random_state = random_state)
    classifier.fit(self.Xtrain, self.ytrain)
    self.y_pred = classifier.predict(self.Xtest)

    self.report()

  def classificationReport(self):
    from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
    print("Accuracy:", accuracy_score(self.ytest, self.y_pred))
    print(classification_report(self.ytest, self.y_pred))

  def confusionMatrix(self):
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(self.ytest, self.y_pred)
    print(cm)

  def report(self):
    self.confusionMatrix()
    self.classificationReport()

In [128]:
classifier = Classifier(X, y)

In [129]:
classifier.kNN(k=2)

KNN Algorithm
[[64  3]
 [ 1 41]]
Accuracy: 0.963302752293578
              precision    recall  f1-score   support

           0       0.98      0.96      0.97        67
           1       0.93      0.98      0.95        42

    accuracy                           0.96       109
   macro avg       0.96      0.97      0.96       109
weighted avg       0.96      0.96      0.96       109

In [130]:
classifier.svm()

SVM Algorithm
[[65  2]
 [ 1 41]]
Accuracy: 0.9724770642201835
              precision    recall  f1-score   support

           0       0.98      0.97      0.98        67
           1       0.95      0.98      0.96        42

    accuracy                           0.97       109
   macro avg       0.97      0.97      0.97       109
weighted avg       0.97      0.97      0.97       109

In [131]:
classifier.randomForest(n_estimators = 10, criterion = 'entropy', random_state = 0)

Random Forest Algorithm
[[65  2]
 [ 1 41]]
Accuracy: 0.9724770642201835
              precision    recall  f1-score   support

           0       0.98      0.97      0.98        67
           1       0.95      0.98      0.96        42

    accuracy                           0.97       109
   macro avg       0.97      0.97      0.97       109
weighted avg       0.97      0.97      0.97       109